### ISSUE TITLE
(mrp_bom_version + mrp_inverse) view problem

### ISSUE THREAD

**Issue by oihane** [avanzosc/odoo-addons#329]
![fireshot capture 18 - lista de materiales ldm - odoo_ - http___demo odoomrp com_web](https://cloud.githubusercontent.com/assets/2323616/20237205/085f63f0-a8cc-11e6-8b73-39145354e649.png)

If mrp_inverse and mrp_bom_version are both installed the view is shown as previous image. The problem is that mrp.bom does not have a header and that both modules create one, so they overlap.

**Comment by agaldona** [comment]
I changed that button to the page section. If you have the latest version of the module you must have the problem solved.

**Comment by oihane** [comment]
OK, it is a problem in the server that is linked an old version of the module.
